services:
  api:
    image: hangoverhgv/ssh-manager:1.0
    ports:
      - "8000:8000"
    container_name: "SSH-Manager"
    restart: always
    command: "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - dev-configs-data:/vol/web/static
    environment:
      POSTGRES_HOST: db
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: changeme
      POSTGRES_PORT: 5432
      SUPERUSER_SECRET_TOKEN: "supersecret"
      SECRET_KEY: "SecretKey"
    depends_on:
      - db

  db:
    image: postgres:latest
    volumes:
      - db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: devdb
      POSTGRES_USER: devuser
      POSTGRES_PASSWORD: changeme

volumes:
  db-data:
  dev-configs-data:
