name: Build and Deploy

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-linux.txt
        sudo apt-get update
        sudo apt-get install -y ruby ruby-dev rubygems build-essential
        sudo gem install --no-document fpm

    - name: Build the application
      run: |
        pyinstaller --onefile --noconsole main.py

    - name: Create .deb package
      run: |
        chmod +x build_deb.sh
        ./build_deb.sh

    - name: Extract tag name from commit message
      id: extract_tag
      run: |
        TAG_NAME=$(git log -1 --pretty=%B | grep -oP 'tag:\s?v\d+\.\d+\.\d+')
        echo "TAG_NAME=$TAG_NAME" >> $GITHUB_ENV
    - name: Create Git tag
      run: |
        git tag ${{ env.TAG_NAME }}
        git push origin ${{ env.TAG_NAME }}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Verify tag exists
      run: |
        if ! git rev-parse "$TAG_NAME" >/dev/null 2>&1; then
          echo "Tag $TAG_NAME does not exist."
          exit 1
        fi
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      with:
        tag_name: ${{ env.TAG_NAME }}
        release_name: Release ${{ env.TAG_NAME }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.ACTIONS_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./ssh-manager_${{ env.TAG_NAME }}_amd64.deb
        asset_name: ssh-manager_${{ env.TAG_NAME }}_amd64.deb
        asset_content_type: application/x-debian-package
